#include "stm32f10x.h" 
#include "stm32f10x_gpio.h"

void USART1Init(void)
{
RCC->APB2ENR |= RCC_APB2ENR_USART1EN; 
RCC->APB2ENR |= RCC_APB2ENR_IOPAEN; 
GPIOA->CRH &= (~GPIO_CRH_CNF9_0);
GPIOA->CRH |= (GPIO_CRH_CNF9_1 | GPIO_CRH_MODE9);
GPIOA->CRH &= (~GPIO_CRH_CNF10_0);
GPIOA->CRH |= GPIO_CRH_CNF10_1;
GPIOA->CRH &= (~(GPIO_CRH_MODE10));
GPIOA->BSRR |= GPIO_ODR_ODR10;
	
USART1->CR1 = USART_CR1_UE;
USART1->BRR = 7500;
USART1->CR1 |= USART_CR1_TE | USART_CR1_RE | USART_CR1_RXNEIE;
USART1->CR2 = 0;
USART1->CR3 = 0;
}

